limit_req_zone $binary_remote_addr zone=api_limit:10m rate=25r/s; # Rate limit


server {
    listen 80;
    charset utf8;

    location / {
        root /static;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        limit_req zone=api_limit burst=100 nodelay;
        limit_req_status 429;
        error_page 429 = @ratelimit;

        proxy_pass http://fastapi_app:8000/api;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/(docs|redoc|openapi.json) {
        proxy_pass http://fastapi_app:8000$request_uri;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location @ratelimit {
        default_type application/json;
        return 429 '{"detail":"Too Many Requests"}';
    }

    access_log /dev/stdout;
    error_log /dev/stderr;
}